//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peregrine_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentralIndexKey
    {
        public int CentralIndexKeyID { get; set; }
        public string Symbol { get; set; }
        public int CIK { get; set; }
    }
}
