//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Peregrine_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PeregrineResearchEntities : DbContext
    {
        public PeregrineResearchEntities()
            : base("name=PeregrineResearchEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentralIndexKey> CentralIndexKeys { get; set; }
        public virtual DbSet<Clean_datum> Clean_Data { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Web_Result> Web_Results { get; set; }
    }
}
